### PR TITLE
Track DHCP lease information

### PR DESCRIPTION
**Pull request by dturn**
@dalehamel @dwradcliffe

### CODE REVIEW

**Comment by dalehamel** [comment]
@dturn what's the advantage to keeping track of this? i'm concerned it will get out of date.

Then again, if we do this, it will probably help us down the road when we get rid of de-dhcp, as it'll make this data much easier to find.

**Comment by dturn** [comment]
It was a line item on my original TODO list `Nodes whose MAC address has no valid lease` Perhaps I mis understood?

**Comment by dalehamel** [comment]
ohhh, gotcha.

I wonder if we can also do this for IPMI?

**Comment by dturn** [comment]
> I wonder if we can also do this for IPMI?

Probably but do we need / want to if we have Ichinga doing address checks?

**Comment by dalehamel** [comment]
> Probably but do we need / want to if we have Ichinga doing address checks? 

Good point.

This looks good to me.

**Comment by berlincount** [comment]
Looks good to me as well.

**Comment by dturn** [comment]
@berlincount We closed the corresponding Genesis PR w/o merging. I don't remember why, but I'm assuming we had a reason. Going to close this too.

**Pull request closed without merging**
